first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

first_project/first_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^formpage/',views.form_name_view, name='form_name'),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='logout'),
]

first_project/first_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name=models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic=models.ForeignKey(Topic)
    name=models.CharField(max_length=264,unique=True)
    url=models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name=models.ForeignKey(Webpage)
    date=models.DateField()

    def __str__(self):
        return str(self.date)

class UserProfileInfo(models.Model):
    #extending the model using onetoone mapping
    user = models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


#Add custom validators
def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError('Name needs to start with a Z')

class FormName(forms.Form):
    #name=forms.CharField(validators=[check_for_z])
    name=forms.CharField()
    email=forms.EmailField()
    verify_email=forms.EmailField(label="Enter your email again: ")
    text=forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super(FormName,self).clean();
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError('Make sure emails match')


    #Using django validators
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    # This is the way if not using django validator
    # botcatcher = forms.CharField(required=False,
    #                              widget=forms.HiddenInput)
    #
    # def clean_botcatcher(self):
    #     botcacher = self.cleaned_data['botcatcher']
    #     if len(botcacher) > 0:
    #         raise forms.ValidationError("Gotcha Bot")
    #     return botcacher

first_project/first_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Topic,Webpage,AccessRecord
from first_app import forms
from first_app.forms import UserForm, UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list}
    return render(request,'first_app/index.html',context=date_dict)
    #my_dict = {'insert_me': 'Hello I am from views.py'}
    #return render(request,'first_app/index.html',context=my_dict)

def form_name_view(request):
    form=forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            #Do something Here
            print("Validation successful")
            print("Name : " + form.cleaned_data['name'])
            print("Email: " + form.cleaned_data['email'])
            print("Text : " + form.cleaned_data['text'])
    return render(request,'first_app/form_page.html',{'form':form})

def other(request):
    context_dict={'text':'hello world', 'number':100}
    return render(request,'first_app/other.html',context_dict)

def relative(request):
    return render(request,'first_app/relative_url_templates.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password (user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/registration.html',
                            {'user_form':user_form,
                             'profile_form':profile_form,
                             'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account Not Active')
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse('Invalid Login Details supplied')
    else:
        return render(request, 'first_app/login.html', {})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:other' %}">Other</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'first_app:user_login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside this will be inherited if extended -->
      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <h1>Welome to the Forms Page</h1>
    <div class="container">
      <form method="post">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" name="" value="Submit">
      </form>

    </div>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load staticfiles %}
    <!-- <link rel="stylesheet" href="{% static "css/mystyle.css" %}"> -->
  {% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <h1>Hello this is index.html</h1>
        <h2>Goto to /formpage to fill out the form</h2>
      </div>
    </div>
    <!-- {{ insert_me }} -->

    <div class="container">
      <h2>Here are your access records:</h2>
      <div class="djangotwo">
        {% if access_records %}
        <table>
          <thead>
            <th>Site Name</th>
            <th>Date Accessed</th>
          </thead>
          {% for i in access_records %}
          <tr>
            <td>{{ i.name }}</td>
            <td>{{ i.date }}</td>
          </tr>
          {% endfor %}
        </table>
        {% else %}
          <p>No Access Records found</p>
        {% endif %}

      </div>
    </div>
    <div class="container">
      <h1>This is me testing a static image</h1>
      <img src="{% static "images/django.jpg" %}" alt="oops image not found">
    </div>

    {% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'first_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance</h2>

    <h3>{{ text|upper}}</h3>
    <h3>{{ text|cut:'world'}}</h3>
    <h3>{{ number|add:"99" }}</h3>
  {% endblock %}

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load staticfiles %}
    <!-- <link rel="stylesheet" href="{% static "css/mystyle.css" %}"> -->
  {% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register Here</h1>
      <h3>Fillout the form:</h3>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p}}
        {{ profile_form.as_p}}
        <input type="submit" name="" value="Register">
      </form>

    {% endif %}


  </div>
    {% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'first_app:other' %}">Other page</a>
    <a href="{% url 'admin:index' %}">Admin Page</a>
    <a href="{% url 'index' %}">Admin Page</a>

  </body>
</html>